name: Build and Push All Images to ONE ECR Repo

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-north-1
      ECR_REPOSITORY: fullstack-repo
      ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.eu-north-1.amazonaws.com

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # ------------------------------
    # AWS Login
    # ------------------------------
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      uses: aws-actions/amazon-ecr-login@v2

    # ------------------------------
    # Build & Push Frontend
    # ------------------------------
    - name: Build Frontend Image
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:frontend ./client

    - name: Push Frontend Image
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:frontend

    # ------------------------------
    # Build & Push Backend
    # ------------------------------
    - name: Build Backend Image
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:backend ./backend

    - name: Push Backend Image
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:backend

    # ------------------------------
    # Build & Push MySQL
    # ------------------------------
    - name: Build MySQL Image
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:mysql ./mysql

    - name: Push MySQL Image
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:mysql
